### ISSUE TITLE
sound observations

### ISSUE THREAD

**Issue by OtariOboladzeSfC** [ScienceForChange/SoundCollect_backend#13]
I'll put the main parameters of the sound observation here for the reference:

- **Acoustics** (from sound to fixed parameters)
- **Psycho-acoustic** (general questions about space perceptions by users)
- **Meta** (pictures, weather, location...)

**Comment by OtariOboladzeSfC** [comment]
Can you confirm that uploading pictures work? what are the limitations? file size, amount, to to upload, fail massage if something goes wrong @CarlosMillanSfC

**Comment by OtariOboladzeSfC** [comment]
@CarlosMillanSfC is weather API done in the OdourCollect? can we bring it to SoundCollect?

**Comment by CarlosMillanSfC** [comment]
> Can you confirm that uploading pictures work? what are the limitations? file size, amount, to to upload, fail massage if something goes wrong @CarlosMillanSfC

The uploading is working and the limitations are (i put them just to test, they are not like the norma says):

Rhe types of images that can be uploaded only JPEG and PNG images are allowed.

The minimum file size for the images, is specified in kilobytes, each image be at least 128 kilobytes.

The maximum file size for the images, again, the size is specified in kilobytes, requires that each image be no more than 120 megabytes.

The dimensions of the image, each image be no more than 1000 pixels wide and 500 pixels high.

@OtariOboladzeSfC Do you know where I can find the limitations of the norma? I have already the sounds documents so I can look for it there but if you have it its better :D

**Comment by CarlosMillanSfC** [comment]
> @CarlosMillanSfC is weather API done in the OdourCollect? can we bring it to SoundCollect?

Its not, we are working on it and Alberto is gonna meet with johana to narrow some details and help us decide how to do it properly and more efective.

**Comment by CarlosMillanSfC** [comment]
Hola @OtariOboladzeSfC has hecho/empezado/algo con: 
- Psycho-acoustic (general questions about space perceptions by users) ?
Porque hasta que matlab no me de una licencia SDK para trabajar no puedo avanzar en la traducción del sonido a parámetros con el código de ICR y por ponerme con esto.
