### ISSUE TITLE
Get info of the device uploading a sound.

### ISSUE THREAD

**Issue by CarlosMillanSfC** [ScienceForChange/SoundCollect_backend#22]
Oto me pidió que buscara de dónde sacar información sobre el dispositivo que subía el sonido para imagino poder sacar info del hardware del mismo (micrófono y eso) y así poder calibrar el sonido que ha subido de una forma más precisa.

Lo primero que pensamos fue en el objeto request de la petición que envía en sus cabeceras metadatos como la IP y otros, un ejemplo sacado de postman sería:

```
Accept: application/json
Content-Type: multipart/form-data; boundary=--------------------------504027672992432765525468
Authorization: Bearer 61|AKrFut7vh0kZm5gn4LEfR7CPAW3eOjG6t3dbk4Zl110286c9
User-Agent: PostmanRuntime/7.36.3
Cache-Control: no-cache
Postman-Token: 9c062c0f-167a-4c49-b6d7-cc97a1a6cb92
Host: soundcollectapp.com
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 1008458
```

De aquí el que más creo que podría servirnos es la cabecera "User-Agent" que desde pc yo sé que envía datos del navegador (estilo versión, cual, etc.) y quería ver desde el móvil.

Puse unos logs en producción para sacar info de esa cabecera y me da esto:

> [2024-03-07 11:53:39] production.ALERT: Mozilla/5.0 (Linux; Android 12; **M2102J20SG** Build/SKQ1.211006.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.64 Mobile Safari/537.36

(en producción porque claro, tengo que ver qué cabeceras se envían desde el móvil y así comprobar lo más acorde al caso de uso posible).

De esa cadena de datos la más interesante parece ser: **M2102J20SG** que al buscar en google veo que es como un "identificador de dispositivio", según chatGPT

> YO
> what does this mean in a phone? M2102J20SG
> 
> ChatGPT
> The code "M2102J20SG" appears to be a model or device identification number for a mobile phone. However, without additional context, it's challenging to provide specific information about the device. Phone model codes are typically used by manufacturers to distinguish between different variations or versions of their devices.
> 
> If you have more details or context about the phone or the brand it belongs to, I may be able to provide more information. Alternatively, you can search online using the model code along with the brand name to find specific details about the phone.

Después de hablar con Oto confirmamos que es una info que nos sirve y veremos si hay una API que al pasar este dato nos devuelva info del dispositivo (con tener la marca ya sería lo mínimo suficiente) y de momento he encontrado esta:
https://deviceinfohw.ru/devices/

**Comment by OtariOboladzeSfC** [comment]
can we get something line "MPN to model" API? @CarlosMillanSfC 
![image](https://github.com/ScienceForChange/soundCollect/assets/116548840/d5dca7dd-62c1-41bd-ac77-4710d8958d32)

**Comment by OtariOboladzeSfC** [comment]
maybe GSMarena has some API for that? or PhoneArena?
