### ISSUE TITLE
Sound types

### ISSUE THREAD

**Issue by OtariOboladzeSfC** [ScienceForChange/SoundCollect_backend#25]
@JohanaSfC do sound types need to be in CAT? now its ENG

**Comment by CarlosMillanSfC** [comment]
@OtariOboladzeSfC Sound types are in CAT, they appear in english a short span of time but they are supposed to be in CAT (but can be in any language)

| Name | Description |
|--------|--------|
| Sons naturals | Cant dels ocells, seguiment de l'aigua, vent en la vegetació |
| Éssers humans | Converses, riures, nens/as, jugant, trepitjades |
| Soroll del trànsit | Cotxes, autobusos, trens, avions |
| Altres sorolls | Sirenes, construcció, indústria, càrrega de mercaderies |
