### ISSUE TITLE
empty array vs NULL value for images

### ISSUE THREAD

**Issue by OtariOboladzeSfC** [ScienceForChange/SoundCollect_backend#36]
Database should save empty array  "[]" instead of NULL if there are no images associated with the observation

**Comment by CarlosMillanSfC** [comment]
Hola, revisando las issues he visto esta y esto podría solucionarse con este cambio en la clase `api/app/Http/Resources/ObservationResource.php`
```
[...]
'images' => $this->images ?? [],
[...]
```
https://github.com/ScienceForChange/SoundCollect_backend/blob/ca7d386df8b4447a5a6b39bc07ec0e6a3ec722d8/api/app/Http/Resources/ObservationResource.php#L35
No hago el cambio ni nada porque no sé si puede romper algo en front y tal, me dices @OtariOboladzeSfC
