### ISSUE TITLE
Guardar nombre del método con que han calibrado dispositivo

### ISSUE THREAD

**Issue by OtariOboladzeSfC** [ScienceForChange/SoundCollect_backend#64]
añadir "calibration_method" columna a la tabla de usuarios que será 'foreign_key', para guardar el método con qué han calibrado el dispositivo.

Tabla 'calibration_methods' tendrá siguiente información:

id, name 
1,  sonometro
2, microfono exterior
3, dispositivo calibrado
4, sin referencia

"calibration_method" referirá a 'id' de la tabla 'calibration_methods'.

"calibration_method" puede tener valor NULL, onUpdate->cascade, onDelete->restrict

**Comment by CarlosMillanSfC** [comment]
Agregada la tabla y las relaciones
