### ISSUE TITLE
Reset-password endpoint

### ISSUE THREAD

**Issue by OtariOboladzeSfC** [ScienceForChange/SoundCollect_backend#73]
Hay que comprobar si este endpoint funciona correctamente: 

Route::post('/reset-password', \App\Http\Controllers\Auth\NewPasswordController::class)
    ->middleware(['guest:sanctum'])
    ->name('password.store');

**Comment by CarlosMillanSfC** [comment]
Comprobadi y funciona @OtariOboladzeSfC
